views/main.py
import base64
import math
import re
from datetime import datetime, timedelta
from ipaddress import ip_address

import flask
from flask_paginate import Pagination

from nyaa import models
from nyaa.extensions import db
from nyaa.search import (DEFAULT_MAX_SEARCH_RESULT, DEFAULT_PER_PAGE, SERACH_PAGINATE_DISPLAY_MSG,
                         _generate_query_string, search_db, search_db_baked, search_elastic)
from nyaa.utils import chain_get
from nyaa.views.account import logout

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.app_errorhandler(404)
def not_found(error):
    return flask.render_template('404.html'), 404


@bp.before_app_request
def before_request():
    flask.g.user = None
    if 'user_id' in flask.session:
        user = models.User.by_id(flask.session['user_id'])
        if not user:
            return logout()

        # Logout inactive and banned users
        if user.status != models.UserStatusType.ACTIVE:
            return logout()

        flask.g.user = user

        if 'timeout' not in flask.session or flask.session['timeout'] < datetime.now():
            flask.session['timeout'] = datetime.now() + timedelta(days=7)
            flask.session.permanent = True
            flask.session.modified = True

        if not app.config['MAINTENANCE_MODE']:
            ip = ip_address(flask.request.remote_addr)
            if user.last_login_ip != ip:
                user.last_login_ip = ip.packed
                db.session.add(user)
                db.session.commit()

    # Check if user is banned on POST
    if flask.request.method == 'POST':
        ip = ip_address(flask.request.remote_addr).packed
        banned = models.Ban.banned(None, ip).first()
        if banned:
            if flask.g.user:
                return logout()

            return 'You are banned.', 403


@bp.route('/rss', defaults={'rss': True})
@bp.route('/', defaults={'rss': False})
def home(rss):
    render_as_rss = rss
    req_args = flask.request.args
    if req_args.get('page') == 'rss':
        render_as_rss = True

    search_term = chain_get(req_args, 'q', 'term')

    sort_key = req_args.get('s')
    sort_order = req_args.get('o')

    category = chain_get(req_args, 'c', 'cats')
    quality_filter = chain_get(req_args, 'f', 'filter')

    user_name = chain_get(req_args, 'u', 'user')
    page_number = chain_get(req_args, 'p', 'page', 'offset')
    try:
        page_number = max(1, int(page_number))
    except (ValueError, TypeError):
        page_number = 1

    # Check simply if the key exists
    use_magnet_links = 'magnets' in req_args or 'm' in req_args

    results_per_page = app.config.get('RESULTS_PER_PAGE', DEFAULT_PER_PAGE)

    user_id = None
    if user_name:
        user = models.User.by_username(user_name)
        if not user:
            flask.abort(404)
        user_id = user.id

    special_results = {
        'first_word_user': None,
        'query_sans_user': None,
        'infohash_torrent': None
    }
    # Add advanced features to searches (but not RSS or user searches)
    if search_term and not render_as_rss and not user_id:
        # Check if the first word of the search is an existing user
        user_word_match = re.match(r'^([a-zA-Z0-9_-]+) *(.*|$)', search_term)
        if user_word_match:
            special_results['first_word_user'] = models.User.by_username(user_word_match.group(1))
            special_results['query_sans_user'] = user_word_match.group(2)

        # Check if search is a 40-char torrent hash (or 32-char base32 hash)
        infohash_match = re.match(r'(?i)^([a-f0-9]{40})$', search_term)
        base32_infohash_match = re.match(r'(?i)^([a-z0-9]{32})$', search_term)
        if infohash_match:
            # Check for info hash in database
            matched_torrent = models.Torrent.by_info_hash_hex(infohash_match.group(1))
            special_results['infohash_torrent'] = matched_torrent
        elif base32_infohash_match:
            # Convert base32 to info_hash
            info_hash = base64.b32decode(base32_infohash_match.group(1))
            matched_torrent = models.Torrent.by_info_hash(info_hash)
            special_results['infohash_torrent'] = matched_torrent

    query_args = {
        'user': user_id,
        'sort': sort_key or 'id',
        'order': sort_order or 'desc',
        'category': category or '0_0',
        'quality_filter': quality_filter or '0',
        'page': page_number,
        'rss': render_as_rss,
        'per_page': results_per_page
    }

    if flask.g.user:
        query_args['logged_in_user'] = flask.g.user
        if flask.g.user.is_moderator:  # God mode
            query_args['admin'] = True

    infohash_torrent = special_results.get('infohash_torrent')
    if infohash_torrent:
        # infohash_torrent is only set if this is not RSS or userpage search
        flask.flash(flask.Markup('You were redirected here because '
                                 'the given hash matched this torrent.'), 'info')
        # Redirect user from search to the torrent if we found one with the specific info_hash
        return flask.redirect(flask.url_for('torrents.view', torrent_id=infohash_torrent.id))

    # If searching, we get results from elastic search
    use_elastic = app.config.get('USE_ELASTIC_SEARCH')
    if use_elastic and search_term:
        query_args['term'] = search_term

        max_search_results = app.config.get('ES_MAX_SEARCH_RESULT', DEFAULT_MAX_SEARCH_RESULT)

        # Only allow up to (max_search_results / page) pages
        max_page = min(query_args['page'], int(math.ceil(max_search_results / results_per_page)))

        query_args['page'] = max_page
        query_args['max_search_results'] = max_search_results

        query_results = search_elastic(**query_args)

        if render_as_rss:
            return render_rss(
                '"{}"'.format(search_term), query_results,
                use_elastic=True, magnet_links=use_magnet_links)
        else:
            rss_query_string = _generate_query_string(
                search_term, category, quality_filter, user_name)
            max_results = min(max_search_results, query_results['hits']['total']['value'])
            # change p= argument to whatever you change page_parameter to or pagination breaks
            pagination = Pagination(p=query_args['page'], per_page=results_per_page,
                                    total=max_results, bs_version=3, page_parameter='p',
                                    display_msg=SERACH_PAGINATE_DISPLAY_MSG)
            return flask.render_template('home.html',
                                         use_elastic=True,
                                         pagination=pagination,
                                         torrent_query=query_results,
                                         search=query_args,
                                         rss_filter=rss_query_string,
                                         special_results=special_results)
    else:
        # If ES is enabled, default to db search for browsing
        if use_elastic:
            query_args['term'] = ''
        else:  # Otherwise, use db search for everything
            query_args['term'] = search_term or ''

        if app.config['USE_BAKED_SEARCH']:
            query = search_db_baked(**query_args)
        else:
            query = search_db(**query_args)

        if render_as_rss:
            return render_rss('Home', query, use_elastic=False, magnet_links=use_magnet_links)
        else:
            rss_query_string = _generate_query_string(
                search_term, category, quality_filter, user_name)
            # Use elastic is always false here because we only hit this section
            # if we're browsing without a search term (which means we default to DB)
            # or if ES is disabled
            return flask.render_template('home.html',
                                         use_elastic=False,
                                         torrent_query=query,
                                         search=query_args,
                                         rss_filter=rss_query_string,
                                         special_results=special_results)


def render_rss(label, query, use_elastic, magnet_links=False):
    rss_xml = flask.render_template('rss.xml',
                                    use_elastic=use_elastic,
                                    magnet_links=magnet_links,
                                    term=label,
                                    site_url=flask.request.url_root,
                                    torrent_query=query)
    response = flask.make_response(rss_xml)
    response.headers['Content-Type'] = 'application/xml'
    # Cache for an hour
    response.headers['Cache-Control'] = 'max-age={}'.format(1 * 5 * 60)
    return response

views/site.py
import flask

bp = flask.Blueprint('site', __name__)


# @bp.route('/about', methods=['GET'])
# def about():
#     return flask.render_template('about.html')


@bp.route('/rules', methods=['GET'])
def rules():
    return flask.render_template('rules.html')


@bp.route('/help', methods=['GET'])
def help():
    return flask.render_template('help.html')


@bp.route('/xmlns/nyaa', methods=['GET'])
def xmlns_nyaa():
    return flask.render_template('xmlns.html')


@bp.route('/trusted', methods=['GET'])
def trusted():
    return flask.render_template('trusted.html')

templates/infobubble_content.html
<strong>Put your announcements into <tt>infobubble_content.html</tt>!</strong>

templates/trusted_rules.html
<h1>Trusted rules go here</h1>

templates/upload.html
{% extends "layout.html" %}
{% block title %}Upload Torrent :: {{ config.SITE_NAME }}{% endblock %}
{% block metatags %}
<meta property="og:description" content="Upload a torrent to {{ config.SITE_NAME }}">
{% endblock %}
{% block body %}
{% from "_formhelpers.html" import render_field %}
{% from "_formhelpers.html" import render_upload %}
{% from "_formhelpers.html" import render_markdown_editor %}

<h1>Upload Torrent</h1>
{% if not g.user %}
<p>You are not logged in, and are uploading anonymously.</p>
{% endif %}

<div id="upload-drop-zone"><span>Drop here!</span></div>
<form method="POST" enctype="multipart/form-data">
	{{ upload_form.csrf_token }}

	{% if config.ENFORCE_MAIN_ANNOUNCE_URL %}<p><strong>Important:</strong> Please include <kbd>{{ config.MAIN_ANNOUNCE_URL }}</kbd> in your trackers.</p>{% endif %}
	<p><strong>Important:</strong> Make sure you have read <strong><a href="{{ url_for('site.rules') }}">the rules</a></strong> before uploading!</p>
	<br>

	{% if show_ratelimit %}
	{% set ratelimit_class = 'danger' if upload_form.ratelimit.errors else 'warning' %}
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-{{ ratelimit_class }}" role="alert">
				<div>You've reached your maximum upload rate ({{ config.MAX_UPLOAD_BURST }} per {{ config.UPLOAD_BURST_DURATION // 60}} minutes, you have <b>{{ ratelimit_count }}</b>) and will now have to wait {{ config.UPLOAD_TIMEOUT // 60 }} minutes between uploads.</div>
				{% if next_upload_time %}
				<div>You may upload again at <b data-timestamp="{{ next_upload_time|utc_timestamp }}">{{ next_upload_time.strftime('%Y-%m-%d %H:%M UTC') }}</b>.</div>
				{% else %}
				<div>You may upload again now.</div>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}

	{% if upload_form.rangebanned.errors %}
	<div class="row">
		<div class="col-md-12">
			<div class="alert alert-danger" role="alert">
				{% for error in upload_form.rangebanned.errors %}
				<p>{{ error }}</p>
				{% endfor %}
			</div>
		</div>
	</div>
	{% endif %}

	<div class="row">
		<div class="col-md-12">
		{{ render_upload(upload_form.torrent_file, accept=".torrent") }}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
		{{ render_field(upload_form.display_name, class_='form-control', placeholder='Display name') }}
		</div>
		<div class="col-md-6">
		{{ render_field(upload_form.category, class_='form-control')}}
		</div>
	</div>
	<div class="row form-group">
		<div class="col-md-6">
			{{ render_field(upload_form.information, class_='form-control', placeholder='Your website or IRC channel') }}
		</div>
		<div class="col-md-6">
			<label class="control-label">Torrent flags</label><br>

			<div class="btn-group" data-toggle="buttons">
				<label class="btn btn-default {% if not g.user %}active disabled{% endif %}" title="Upload torrent anonymously (don't display your username)">
					{{ upload_form.is_anonymous(disabled=(False if g.user else ""), checked=(False if g.user else "")) }}
					{% if not g.user %}<span class="glyphicon glyphicon-ban-circle"></span>{% endif %}
					{% if g.user %}<span class="glyphicon glyphicon-check"></span>{% endif %}
					{% if g.user %}<span class="glyphicon glyphicon-unchecked"></span>{% endif %}
					Anonymous
				</label>
				<label class="btn btn-grey" title="Hide torrent from listing">
					{{ upload_form.is_hidden }}
					<span class="glyphicon glyphicon-check"></span>
					<span class="glyphicon glyphicon-unchecked"></span>
					Hidden
				</label>
			</div>
			<div class="hidden-xl hidden-lg"><br></div>
			<div class="btn-group" data-toggle="buttons">
				<label class="btn btn-danger" title="This torrent is derived from another release">
					{{ upload_form.is_remake }}
					<span class="glyphicon glyphicon-check"></span>
					<span class="glyphicon glyphicon-unchecked"></span>
					Remake
				</label>
				<label class="btn btn-warning" title="This torrent is a complete batch (eg. season)">
					{{ upload_form.is_complete }}
					<span class="glyphicon glyphicon-check"></span>
					<span class="glyphicon glyphicon-unchecked"></span>
					Complete
				</label>
				{% if g.user.is_trusted %}
				<label class="btn btn-success active" title="Mark torrent trusted">
					{{ upload_form.is_trusted(checked="") }}
					<span class="glyphicon glyphicon-check"></span>
					<span class="glyphicon glyphicon-unchecked"></span>
					Trusted
				</label>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			{{ render_markdown_editor(upload_form.description, field_name='description') }}
		</div>
	</div>

	{% if config.USE_RECAPTCHA and (not g.user or g.user.age < config['ACCOUNT_RECAPTCHA_AGE']) %}
	<div class="row">
		<div class="col-md-4">
			{% for error in upload_form.recaptcha.errors %}
			{{ error }}
			{% endfor %}
			{{ upload_form.recaptcha }}
		</div>
	</div>
	{% endif %}

	<br>
	<div class="row">
		<div class="form-group col-md-6">
			<input type="submit" value="Upload" class="btn btn-primary">
		</div>
	</div>
</form>
{% endblock %}

templates/view.html
{% extends "layout.html" %}
{% block title %}{{ torrent.display_name }} :: {{ config.SITE_NAME }}{% endblock %}
{% block metatags %}
{% set uploader_name = torrent.user.username if (torrent.user and not torrent.anonymous) else 'Anonymous' %}
<meta property="og:description" content="{{ category_name(torrent.sub_category.id_as_string) }} | {{ torrent.filesize | filesizeformat(True) }} | Uploaded by {{ uploader_name }} on {{ torrent.created_time.strftime('%Y-%m-%d') }}">
{% endblock %}
{% block body %}
{% from "_formhelpers.html" import render_field %}
<div class="panel panel-{% if torrent.deleted %}deleted{% elif torrent.remake %}danger{% elif torrent.trusted %}success{% else %}default{% endif %}">
	<div class="panel-heading"{% if torrent.hidden %} style="background-color: darkgray;"{% endif %}>
		<h3 class="panel-title">
			{% if can_edit %}
			<a href="{{ url_for('torrents.edit', torrent_id=torrent.id) }}" title="Edit torrent"><i class="fa fa-fw fa-pencil"></i></a>
			{% endif %}
			{{ torrent.display_name }}
		</h3>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-1">Category:</div>
			<div class="col-md-5">
				<a href="{{ url_for('main.home', c=torrent.main_category.id_as_string) }}">{{ torrent.main_category.name }}</a> - <a href="{{ url_for('main.home', c=torrent.sub_category.id_as_string) }}">{{ torrent.sub_category.name }}</a>
			</div>

			<div class="col-md-1">Date:</div>
			<div class="col-md-5" data-timestamp="{{ torrent.created_utc_timestamp|int }}">{{ torrent.created_time.strftime('%Y-%m-%d %H:%M UTC') }}</div>
		</div>

		<div class="row">
			<div class="col-md-1">Submitter:</div>
			<div class="col-md-5">
				{% set user_url = torrent.user and url_for('users.view_user', user_name=torrent.user.username) %}
				{%- if not torrent.anonymous and torrent.user -%}
				<a class="text-{{ torrent.user.userlevel_color }}" href="{{ user_url }}" data-toggle="tooltip" title="{{ torrent.user.userlevel_str }}">{{ torrent.user.username }}</a>
				{%- else -%}
				Anonymous {% if torrent.user and (g.user == torrent.user or g.user.is_moderator) %}(<a class="text-{{ torrent.user.userlevel_color }}" href="{{ user_url }}" data-toggle="tooltip" title="{{ torrent.user.userlevel_str }}">{{ torrent.user.username }}</a>){% endif %}
				{%- endif -%}
				{% if g.user and g.user.is_superadmin and torrent.uploader_ip %}
				({{ torrent.uploader_ip_string }})
				{% endif %}
			</div>

			<div class="col-md-1">Seeders:</div>
			<div class="col-md-5"><span style="color: green;">{% if config.ENABLE_SHOW_STATS %}{{ torrent.stats.seed_count }}{% else %}Coming soon{% endif %}</span></div>

		</div>

		<div class="row">
			<div class="col-md-1">Information:</div>
			<div class="col-md-5">
				{% if torrent.information %}
				{{ torrent.information_as_link | safe }}
				{% else %}
				No information.
				{% endif%}
			</div>

			<div class="col-md-1">Leechers:</div>
			<div class="col-md-5"><span style="color: red;">{% if config.ENABLE_SHOW_STATS %}{{ torrent.stats.leech_count }}{% else %}Coming soon{% endif %}</span></div>
		</div>

		<div class="row">
			<div class="col-md-1">File size:</div>
			<div class="col-md-5">{{ torrent.filesize | filesizeformat(True) }}</div>

			<div class="col-md-1">Completed:</div>
			<div class="col-md-5">{% if config.ENABLE_SHOW_STATS %}{{ torrent.stats.download_count }}{% else %}Coming soon{% endif %}</div>
		</div>
		<div class="row">
			<div class="col-md-offset-6 col-md-1">Info hash:</div>
			<div class="col-md-5"><kbd>{{ torrent.info_hash_as_hex }}</kbd></div>
		</div>
	</div><!--/.panel-body -->

	<div class="panel-footer clearfix">
		{% if torrent.has_torrent %}<a href="{{ url_for('torrents.download', torrent_id=torrent.id )}}"><i class="fa fa-download fa-fw"></i>Download Torrent</a> or {% endif %}<a href="{{ torrent.magnet_uri }}" class="card-footer-item"><i class="fa fa-magnet fa-fw"></i>Magnet</a>
		{% if g.user and g.user.age > config['RATELIMIT_ACCOUNT_AGE'] %}
		<button type="button" class="btn btn-xs btn-danger pull-right" data-toggle="modal" data-target="#reportModal">
			Report
		</button>
		{% endif %}
	</div>
</div><!--/.panel -->

<div class="panel panel-default">
	<div markdown-text class="panel-body" id="torrent-description">
		{%- if torrent.description -%}
		{# Escape newlines into html entities because CF strips blank newlines #}
		{{- torrent.description | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}
		{%- else -%}
		#### No description.
		{%- endif -%}
	</div>
</div>

{% cache 86400, "filelist", torrent.info_hash_as_hex %}
{% if files and files.__len__() <= config.MAX_FILES_VIEW %}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">File list</h3>
	</div>

	<div class="torrent-file-list panel-body">
		<ul>
		{% for key, value in files.items() recursive -%}
		{% if value is iterable %}
			{% set pre_expanded = not loop.depth0 and value.items()|length <= 20 %}
			<li>
				<a href="" class="folder"><i class="fa fa-folder{% if pre_expanded %}-open{% endif %}"></i>{{ key }}</a>
				<ul{% if pre_expanded %} data-show="yes"{% endif %}>{{ '\n' + loop(value.items()) }}
				</ul>
			</li>
		{% else %}
			<li><i class="fa fa-file"></i>{{ key }} <span class="file-size">({{ value | filesizeformat(True) }})</span></li>
		{% endif %}
		{% endfor %}
		</ul>
	</div>
</div><!--/.panel -->
{% elif files %}
<div class="panel panel-default">
	<div class="panel-heading panel-heading-collapse">
		<h3 class="panel-title">
			Too many files to display.
		</h3>
	</div>
</div>
{% else %}
<div class="panel panel-default">
	<div class="panel-heading panel-heading-collapse">
		<h3 class="panel-title">
			File list is not available for this torrent.
		</h3>
	</div>
</div>
{% endif %}
{% endcache %}

<div id="comments" class="panel panel-default">
	<div class="panel-heading">
		<a data-toggle="collapse" href="#collapse-comments" role="button" aria-expanded="{% if g.user and g.user.preferences.hide_comments %}false{% else %}true{% endif %}" aria-controls="collapse-comments">
		<h3 class="panel-title">
			Comments - {{ torrent.comment_count }}
		</h3>
		</a>
	</div>
	<div class="collapse {% if g.user and g.user.preferences.hide_comments %}{% else %}in{% endif %}" id="collapse-comments">
	{% for comment in comments %}
	<div class="panel panel-default comment-panel" id="com-{{ loop.index }}">
		<div class="panel-body">
			<div class="col-md-2">
				<p>
					<a class="text-{{ comment.user.userlevel_color }}" href="{{ url_for('users.view_user', user_name=comment.user.username) }}" data-toggle="tooltip" title="{{ comment.user.userlevel_str }}">{{ comment.user.username }}</a>
					{% if comment.user.id == torrent.uploader_id and not torrent.anonymous %}
					(uploader)
					{% endif %}
				</p>
				<img class="avatar" src="{{ comment.user.gravatar_url() }}" alt="{{ comment.user.userlevel_str }}">
			</div>
			<div class="col-md-10 comment">
				<div class="row comment-details">
					<a href="#com-{{ loop.index }}"><small data-timestamp-swap data-timestamp="{{ comment.created_utc_timestamp|int }}">{{ comment.created_time.strftime('%Y-%m-%d %H:%M UTC') }}</small></a>
					{% if comment.edited_time %}
					<small data-timestamp-swap data-timestamp-title data-timestamp="{{ comment.edited_utc_timestamp }}" title="{{ comment.edited_time }}">(edited)</small>
					{% endif %}
					<div class="comment-actions">
						{% if g.user.id == comment.user_id and not comment.editing_limit_exceeded and (not torrent.comment_locked or comment_form) %}
						<button class="btn btn-xs edit-comment" title="Edit"{% if config.EDITING_TIME_LIMIT %} data-until="{{ comment.editable_until|int }}"{% endif %}>Edit</button>
						{% endif %}
						{% if g.user.is_superadmin or (g.user.id == comment.user_id and not torrent.comment_locked and not comment.editing_limit_exceeded) %}
						<form class="delete-comment-form" action="{{ url_for('torrents.delete_comment', torrent_id=torrent.id, comment_id=comment.id) }}" method="POST">
							<button name="submit" type="submit" class="btn btn-danger btn-xs" title="Delete">Delete</button>
						</form>
						{% endif %}
					</div>
				</div>
				<div class="row comment-body">
					{# Escape newlines into html entities because CF strips blank newlines #}
					<div markdown-text class="comment-content" id="torrent-comment{{ comment.id }}">{{- comment.text | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}</div>
					{% if g.user.id == comment.user_id and comment_form %}
					<form class="edit-comment-box" action="{{ url_for('torrents.edit_comment', torrent_id=torrent.id, comment_id=comment.id) }}" method="POST">
						{{ comment_form.csrf_token }}
						<div class="form-group">
							<textarea class="form-control" name="comment" autofocus>{{- comment.text | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}</textarea>
						</div>
						{% if config.USE_RECAPTCHA and g.user.age < config['ACCOUNT_RECAPTCHA_AGE'] %}
						<div class="row">
							<div class="col-md-4">
								{% if comment_form.recaptcha.errors %}
								<div class="alert alert-danger">
									<p><strong>CAPTCHA error:</strong></p>
									<ul>
										{% for error in comment_form.recaptcha.errors %}
										<li>{{ error }}</li>
										{% endfor %}
									</ul>
								</div>
								{% endif %}
								{{ comment_form.recaptcha }}
							</div>
						</div>
						{% endif %}
						<input type="submit" value="Submit" class="btn btn-success btn-sm">
						<button class="btn btn-sm edit-comment" title="Cancel">Cancel</button>
						<span class="edit-error text-danger"></span>
						<div class="edit-waiting" style="display:none"></div>
					</form>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	{% endfor %}
	{% if torrent.comment_locked %}
	<div class="alert alert-warning">
		<p>
			<i class="fa fa-lock" aria-hidden="true"></i>
			Comments have been locked.
		</p>
	</div>
	{% endif %}
	{% if comment_form %}
	<form class="comment-box" method="POST">
		{{ comment_form.csrf_token }}
		<div class="row">
			<div class="col-md-12">
				{{ render_field(comment_form.comment, class_='form-control') }}
			</div>
		</div>
		{% if config.USE_RECAPTCHA and g.user.age < config['ACCOUNT_RECAPTCHA_AGE'] %}
		<div class="row">
			<div class="col-md-4">
				{% if comment_form.recaptcha.errors %}
				<div class="alert alert-danger">
					<p><strong>CAPTCHA error:</strong></p>
					<ul>
						{% for error in comment_form.recaptcha.errors %}
						<li>{{ error }}</li>
						{% endfor %}
					</ul>
				</div>
				{% endif %}
				{{ comment_form.recaptcha }}
			</div>
		</div>
		{% endif %}
		<div class="row">
			<div class="col-md-12">
				<input type="submit" value="Submit" class="btn btn-success btn-sm">
			</div>
		</div>
	</form>
	{% endif %}
	</div>
</div>

{% if g.user and g.user.age > config['RATELIMIT_ACCOUNT_AGE'] %}
<div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
						aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Report torrent #{{ torrent.id }}</h4>
			</div>
			<div class="modal-body">
				<div class="alert alert-warning" role="alert">
					Before submitting a report, please check that the torrent
					actually breaks <a href="{{ url_for('site.rules') }}">the
					rules</a>. Useless reports like "download is slow" or
					"thanks" can get you banned from the site.
				</div>
				<form method="POST" action="{{ url_for('torrents.report', torrent_id=torrent.id) }}">
					{{ report_form.csrf_token }}
					{{ render_field(report_form.reason, class_='form-control', maxlength=255) }}
					<div style="float: right;">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="submit" id="reportSubmit" class="btn btn-danger">Report</button>
					</div>
				</form>
			</div>
			<div class="modal-footer" style="border-top: none;">
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	// Focus the report text field once the modal is opened.
	$('#reportModal').on('shown.bs.modal', function () {
		$('#reason').focus();
		$('#reportSubmit').attr('disabled', true);
	});
	$('#reason').on('input', function(e) {
		if($('#reason').val().length > 0) {
			$('#reportSubmit').removeAttr('disabled');
		} else {
			$('#reportSubmit').attr('disabled', true);
		}
	});
</script>
{% endif %}

{% endblock %}